-- ALERT SYSTEM 
SELECT T.USERS_ID,
CASE 
   WHEN AVG(B.FOCUS_SCORE) < 4 AND AVG(T.TIME_PRESSURE) > 8 THEN 'NEED IMMEDIATE BREAK' 
   ELSE 'NO_BREAK' 
   END AS REQUIRED_BREAK_NECESSITY
   FROM TASKS T JOIN BEHAVIOUR_LOGS B ON T.USERS_ID=B.USERS_ID GROUP BY T.USERS_ID ;
 -- CLASSIFICATION CORE LOGIC   
SELECT U.USERS_ID , 
CASE 
   WHEN AVG(T.DIFFICULTY)>7 AND AVG(T.TIME_PRESSURE)> 7 THEN 'OVERLOADED' 
   WHEN AVG(B.FOCUS_SCORE)< 5 THEN 'DRIFTED' ELSE 'NORMAL' 
   END AS USER_STATUS FROM USERS U
   LEFT JOIN TASKS T ON U.USERS_ID =T.USERS_ID 
   LEFT JOIN BEHAVIOUR_LOGS B ON U.USERS_ID =B.USERS_ID 
   GROUP BY U.USERS_ID;
   -- STRESS SCORE CORRELATION 
 SELECT T.USERS_ID ,
 (AVG(TIME_PRESSURE) + AVG(DIFFICULTY)+ AVG(B.DISTRACTION_COUNT)-AVG(B.FOCUS_SCORE)) AS TOTAL_STRESS_INDEX
 FROM TASKS  T INNER JOIN BEHAVIOUR_LOGS B ON T.USERS_ID= B.USERS_ID GROUP BY T.USERS_ID ORDER BY TOTAL_STRESS_INDEX LIMIT 5  ;      
-- AUDIT LOGS 
SELECT USERS_ID,ACTION,TIMESTAMP FROM AUDIT_LOGS ORDER BY TIMESTAMP DESC;              
